import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import {
  ShoppingCartIcon,
  Bars3Icon,
  UserCircleIcon,
  MagnifyingGlassIcon,
} from "@heroicons/react/24/outline";
import NavMenu from "../NavMenu";
type MainLayoutType = {
  title?: string;
};

export default function MainLayout({ title }: MainLayoutType) {
  const [mainNav, setMainNav] = useState(false);
  const [show, setShow] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  const controlNavbar = () => {
    if (typeof window !== "undefined") {
      if (
        window.scrollY - 0.01 * window.innerHeight > lastScrollY &&
        window.scrollY > 0.2 * window.innerHeight
      ) {
        // if scroll down hide the navbar
        setShow(false);
      }
      if (
        window.scrollY < lastScrollY - 0.01 * window.innerHeight ||
        window.scrollY < 0.2 * window.innerHeight ||
        mainNav
      ) {
        // if scroll up show the navbar
        setShow(true);
      }

      // remember current page location to use in the next move
      setLastScrollY(window.scrollY);
    }
  };
  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener("scroll", controlNavbar);

      // cleanup function
      return () => {
        window.removeEventListener("scroll", controlNavbar);
      };
    }
  });

  return (
    <>
      <Head>
        <title>{title ? title + " - Gozarche" : "فروشگاه گذرچه"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <div
          className={`fixed top-0 z-20 flex w-full justify-between border-b bg-white  px-4 shadow-lg duration-300 ease-in-out ${
            !show && "-translate-y-24"
          }`}
        >
          <nav className="container mx-auto">
            <div className="flex justify-between">
              <div className="flex flex-row items-center">
                <button
                  className="outline-none"
                  onClick={() => setMainNav(!mainNav)}
                  onMouseEnter={() => setMainNav(true)}
                >
                  <Bars3Icon className="mx-2 h-8 w-8 text-gray-500" />
                </button>
                <Link href="/">
                  <Image
                    src="/gozarche logo long.png"
                    width={100}
                    height={40}
                    alt="logo"
                  ></Image>
                </Link>
                <form className='flex items-center h-full px-4 max-md:hidden w-max '>
                  <input
                    type="search"
                    className="bg-gray-5 rounded-lg h-10 m-2 py-2 px-4 hover:rounded-[4rem] w-80 transition-border duration-300 border-2 border-gray-200 text-sm text-gray-900 outline-none "
                    placeholder="جستجو..."
                    required
                  />
                  <button
                    type="submit"
                    className=" relative  my-auto  py-2  left-12 text-sm font-medium  "
                  >
<MagnifyingGlassIcon className='h-8 w-8 text-slate-200 hover:text-slate-400'/>
                  </button>
                </form>
              </div>


              <div className="flex items-center p-2">
                <Link href="/login">
                  <div className=" m-auto my-auto flex items-center transition-border duration-300 rounded-lg hover:rounded-[4rem] border-2 p-2">
                    <UserCircleIcon className="h-6  text-gray-700" />
                    <span className="bold px-2 text-sm">ورود</span>
                  </div>
                </Link>
                <ShoppingCartIcon className="mx-2 h-6 text-gray-700" />
              </div>
            </div>
          </nav>
        </div>
        <NavMenu show={mainNav} setShow={setMainNav}>
          hello
        </NavMenu>
        <div className="p-10"></div>
      </div>
    </>
  );
}
