import Head from "next/head";
  import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import {
  HeartIcon,
  ShoppingCartIcon,
  UserIcon,
  MagnifyingGlassIcon,
  ArrowsUpDownIcon,
} from "@heroicons/react/24/outline";
import { useSession, signIn } from "next-auth/react";
import MobileTabBar from "../navs/MobileTabBar";
import MainFooter from "../footers/mainfooter";
import MegaMenu from "../navs/MegaMenu";
type MainLayoutType = {
  title?: string;
  children?: React.ReactNode;
  topbanner?: boolean;
};
export default function MainLayout({
  title,
  children,
  topbanner,
}: MainLayoutType) {
  const [show, setShow] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);
  const session = useSession();
  const controlNavbar = () => {
    if (typeof window !== "undefined") {
      if (
        window.scrollY - 0.01 * window.innerHeight > lastScrollY &&
        window.scrollY > 0.2 * window.innerHeight
      ) {
        // if scroll down hide the navbar
        setShow(false);
      }
      if (
        window.scrollY < lastScrollY - 0.01 * window.innerHeight ||
        window.scrollY < 0.2 * window.innerHeight
      ) {
        // if scroll up show the navbar
        setShow(true);
      }
      // remember current page location to use in the next move
      setLastScrollY(window.scrollY);
    }
  };
  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener("scroll", controlNavbar);
      // cleanup function
      return () => {
        window.removeEventListener("scroll", controlNavbar);
      };
    }
  });

  return (
    <>
      <Head>
        <title>{title ? title + " - Gozarche" : "فروشگاه گذرچه"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MobileTabBar>
        <div
          className={`fixed top-0 z-20 m-auto w-full justify-between  bg-white shadow-lg  duration-300 ease-in-out max-sm:right-[200vw] `}
        >
          <div
            className={`h-14 bg-secondary-300 text-center ${
              !topbanner && "hidden"
            }`}
          >
            banner
          </div>
          <nav className="w-full">
            <div className="container mx-auto flex h-16 justify-between bg-white ">
              <div className="z-20 flex flex-row items-center bg-white">
                <Link href="/" className="m-2">
                  <Image
                    src="/gozarche logo long.png"
                    width={120}
                    height={50}
                    alt="logo"
                  ></Image>
                </Link>
                <form className="flex h-full w-max items-center px-4 max-md:hidden ">
                  <input
                    type="search"
                    className="bg-gray-5 transition-border  m-2 h-10 w-80 rounded-lg  border-gray-200 py-2 px-4 text-sm text-gray-900 shadow-[0_0_5px_0_rgba(0,0,0,0.2)] outline-none duration-500 hover:rounded-3xl "
                    placeholder="جستجو..."
                    required
                  />
                  <button
                    type="submit"
                    className=" relative  left-12  my-auto  py-2 text-sm font-medium  "
                  >
                    <MagnifyingGlassIcon className="h-8 w-8 text-slate-200 hover:text-slate-400" />
                  </button>
                </form>
              </div>
              <div className="z-10 flex items-center p-2 ">
                {session.status == "loading" ? (
                  <div className="aspect-square bg-slate-400" />
                ) : session.status == "unauthenticated" ? (
                  <button onClick={() => signIn()}>
                    <div className=" transition-border m-auto  flex items-center rounded-lg border-2 p-2 duration-500 hover:rounded-3xl">
                      <UserIcon className="h-6  text-gray-700" />
                      <span className="bold px-2 font-iransans text-sm">
                        ورود
                      </span>
                    </div>
                  </button>
                ) : (
                  <>
                    <span className="px-2">{session.data?.user?.name}</span>
                    <UserIcon className="mx-1 h-6 px-2 text-gray-700" />
                  </>
                )}
                
              </div>
            </div>
            <div
              className={`overflow-clipcontaineer container z-10  m-auto max-sm:hidden duration-500${
                !show ? "h-0" : "h-12 border-t"
              }`}
            >
              <div
                className={`z-0 flex items-center justify-between bg-white duration-500 max-sm:hidden ${
                  !show
                    ? "collapse h-0 -translate-y-14 overflow-hidden"
                    : "h-12"
                }`}
              >
                <MegaMenu className="" margintop={topbanner?"translate-y-[10.5rem]":"translate-y-28"}/>
                <div className='flex'>
                <ShoppingCartIcon className="mx-2 h-6 text-gray-700 max-sm:hidden " />
                <ArrowsUpDownIcon className="mx-2 h-6 text-gray-700 max-sm:hidden " />
                <HeartIcon className="mx-2 h-6 text-gray-700 max-sm:hidden" />
                </div>
                
              </div>
            </div>
          </nav>
        </div>
        <div className="mx-auto min-h-screen">
          <div
            className={`${
              topbanner
                ? "h-[7.5rem] sm:h-[11.5rem]"
                : "w-100 h-[4rem] sm:h-[7.5rem]"
            } `}
          >
            hello
          </div>
          {children}
        </div>
        <MainFooter />
        <div className="max-sm:h-16" />
      </MobileTabBar>
    </>
  );
}
